### ISSUE TITLE
CleanShot X

### ISSUE THREAD

**Issue by Stephen-Lon** [alfredapp/gallery-edits#31]
### Preflight

- [X] The Alfred team has invited me to submit this workflow.

### The submitted workflow:

- [X] Was authored by me. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#authorship)
- [X] Uses [Workflow Configuration](https://www.alfredapp.com/help/workflows/user-configuration/) or has no user-facing settings. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#configuration)
- [X] Does not have an auto-updater. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#auto-updating)
- [X] Does not contain unsigned and non-notarised binaries. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#signed-binaries)
- [X] Does not download extra software. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#downloading-software)
- [X] Uses keywords with more than one character. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#short-keywords)
- [X] Has a descriptive About section. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#about-section)
- [X] Has an icon of at least 256x256 px. [&#9432;](https://github.com/alfredapp/gallery-edits/blob/main/Documentation/Workflow%20Submissions.md#icon-size)

### Homepage

https://github.com/Stephen-Lon/Alfred-workflow-cleanshot/releases/latest/download/cleanshot.alfredworkflow

### Alfred Forum page

https://www.alfredforum.com/topic/16960-cleanshot-x-workflow/?do=findComment&comment=109280

## Usage
See a list of CleanShot X utilities you can trigger from the workflow via the `csx` or `cs` keyword and <kbd>space</kbd>.
<img width="764" alt="Screenshot 2024-03-07 at 15 16 57" src="https://github.com/alfredapp/gallery-edits/assets/111967061/5e2b6291-3af4-4ff5-93b0-a42e345e7631">

### Tags

Screenshots, CleanShot X

**Comment by Stephen-Lon** [comment]
I hope this is OK for a first attempt!

**Comment by vitorgalvao** [comment]
Thank you. It is indeed good for a first attempt. I’ve made several small tweaks, but don’t be discouraged as I list the reasons for all of them.

* Took new screenshots.
  * To make the dark icons more visible.
  * To have one item visibly selected.
  * To include the `csq` option too.
* Included `csq` in the description.
* Only listed one of the keywords, to avoid confusion.

I did not include the forum post for now, as it’s in the middle of a larger thread. If you make a specific thread for the workflow, please let me know and I’ll include that.

You mention requiring the <kbd>space</kbd> after the keyword, but maybe that’s from a previous version? Because it’s not necessary now. In addition, in the internal About you also mention calling it without an argument to start the app but that isn’t possible because the options appear immediately. I think the current behaviour is good, but wanted to point that out.

Finally, and this is something I’ve been forgetting to ask, when providing links to workflows please always provide the home of the repo instead of a direct link to the download. I get that the direct download is useful to regular users, but for my needs the repo’s home is always best.

Thank you again. This is already live at https://alfred.app/workflows/stephenc/cleanshot-x/.
