### ISSUE TITLE
Suggest Edit: artemy/ns-train-schedule

### ISSUE THREAD

**Issue by artemy** [alfredapp/gallery-edits#46]
### Gallery URL

https://alfred.app/workflows/artemy/ns-train-schedule/

### Website

https://github.com/artemy/alfred-ns-schedule/

### Forum

https://www.alfredforum.com/topic/18771-ns-nederlandse-spoorwegen-train-schedule-for-alfred/

### About

I've released new version v4.0 recently

Release page with changelog: https://github.com/artemy/alfred-ns-schedule/releases/tag/v4.0

**Comment by vitorgalvao** [comment]
Thank you for the notice. Since the workflow’s behaviour changed slightly, could you provide a couple more screenshots [with the same theme](https://github.com/artemy/alfred-ns-schedule/raw/master/.readme/images/screenshot.png)? Specifically, one screenshot with `ns` searching for the origin, and another searching for the destination.

Also, I recommend you change the List Filters to `Argument Optional` instead of `Argument Required` as that allows people to see the available stations even before typing. Because Alfred learns from the choice, common choices will begin bubbling to the top.

**Comment by vitorgalvao** [comment]
I took new screenshots since you were using a default theme. I still recommend you update the workflow with `Argument Optional`.

**Comment by artemy** [comment]
Perfect, thanks for the suggestion, I'll make a new release later this week
