### ISSUE TITLE
Suggest Edit: meshchaninov/translate

### ISSUE THREAD

**Issue by meshchaninov** [alfredapp/gallery-edits#63]
### Gallery URL

https://alfred.app/workflows/meshchaninov/translate/

### Website

https://github.com/meshchaninov/alfred-translate-workflow/releases/tag/v0.2.4

### About

Hi, I want to update my workflow.
- increase the number of default characters t -> trns 
- workflow did not work for some users, made a patch

**Comment by vitorgalvao** [comment]
Thank you, but this version doesn’t work as is. On a clean install one gets `ModuleNotFoundError: No module named 'certifi'`. Python packages need to be bundled in the workflow. I have some doubts this is the proper solution. Once shouldn’t just be adding more certificates because *one* user had an issue without first understanding what happened to make the code stop for that one user.

**Comment by vitorgalvao** [comment]
Thank you, but this version doesn’t work as is. On a clean install one gets:

```
ModuleNotFoundError: No module named 'certifi'
```

Python packages need to be bundled in the workflow.

But I wonder if this is the proper solution. Adding more certificates because *one* user had an issue seems excessive. It’s important to understand what happened to make the code stop for that one person. The pull request in question doesn’t even mention an error just “it stopped working and this fixed it” so as far as we know this was just a bandaid for something else the user changed on their machine.

Maybe they’re on a really old version of macOS. Would you want to have to continuously support and update the certifi package in the workflow just to support a discontinued version of macOS (assuming that is the case)? Maybe you do, but I’m asking because workflows in the Gallery are expected to be maintained and stable, so reducing the surface for problems matters.

**Comment by vitorgalvao** [comment]
@meshchaninov Any news on the resolution? Cannot proceed with the update until the above is fixed.

**Comment by meshchaninov** [comment]
Yeah, maybe you're right

I was in a hurry and did not fully understand what the problem was. I do not want to support the older versions, and the author of issue did not clearly explain what the issue was. Therefore, it is best to close this issue. I'll roll out the changes in the code

Thank you for your response and for reviewing my request

**Comment by vitorgalvao** [comment]
@meshchaninov The change to update the keyword was still good, no need to revert that part.
