### ISSUE TITLE
Suggest Edit: soulver/soulver

### ISSUE THREAD

**Issue by orf** [alfredapp/gallery-edits#66]
### Gallery URL

https://alfred.app/workflows/soulver/soulver/

### About

The setup instructions are incorrect: You should visit https://soulver.app/integrations/ and download the alfred workflow from there.

The alfred option does not appear to exist anymore:

<img width="442" alt="Screenshot 2024-08-19 at 11 57 38" src="https://github.com/user-attachments/assets/87a2534a-a09c-49aa-8377-42fd13926587">

**Comment by vitorgalvao** [comment]
The option is still there, but only on the direct download version. On the Mac App Store version, the option isn’t available. It may be due to some Mac App Store restriction.

While the version installed from inside the app has a higher version number than the one on the website, it looks to have more recent features.

I’ll contact the developer then proceed accordingly. Thank you for the heads-up.
